#启动端口
server:
  port: 8989
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.63.216:3306/spring_multi_module?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: wo131421

  ##JPA
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句
    database-platform: org.hibernate.dialect.MySQL5Dialect

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hfh.springbootmultimodule.entity
  global-config:
    #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    id-type: 0
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
  logic-delete-value: -1
  logic-not-delete-value: 0
  #自定义填充策略接口实现
  #meta-object-handler: com.baomidou.springboot.xxx
  #自定义SQL注入器
  sql-injector: com.baomidou.mybatisplus.mapper.AutoSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hfh.springbootmultimodule.dao: DEBUG


